[package]
name = "certificate-SBT"
version = "0.0.1"
authors = ["RandyPen", "KT"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
certificate_sbt =  "0x0"
sui =  "0000000000000000000000000000000000000002"
